In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip install patool -Uqq

     |████████████████████████████████| 77 kB 3.1 MB/s 


In [3]:
import os
import shutil
import patoolib
import pandas as pd
from pathlib import Path
from tqdm import tqdm

In [4]:
filename = '/content/drive/MyDrive/Colab Notebooks/pathshala/unsorted/bangla/alphabet/BanglaLekha-Isolated.zip'
extract_dir = "/content/lekha"
archive_format = "zip"
shutil.unpack_archive(filename, extract_dir, archive_format)

In [5]:
folders = [str(i) for i in range(12,51)]
my_path = []
for folder in tqdm(folders):
    root_path = Path(f'/content/lekha/BanglaLekha-Isolated/Images/{folder}')
    label = int(folder)-12
    files = os.listdir(root_path)
    files.sort()
    for f in files:
        if f != 'Thumbs.db':
            my_path.append((root_path/f , label))
        else:
            print("FUCK")
    
len(my_path)

100%|██████████| 39/39 [00:00<00:00, 55.68it/s]


77167

In [6]:
my_path[21500]

(PosixPath('/content/lekha/BanglaLekha-Isolated/Images/22/02_0002_1_19_1016_1600_22.png'),
 10)

In [7]:
target = Path('/content/capital')
if not os.path.isdir(target):
    os.mkdir(target)

for i in tqdm(my_path):
    original, num = i   
    file_name = (f"{num:02}_"+original.parts[-1])
    shutil.copyfile(original, target/file_name)
    


100%|██████████| 77167/77167 [00:08<00:00, 9116.92it/s] 


In [8]:
filename = '/content/drive/MyDrive/Colab Notebooks/pathshala/unsorted/bangla/EkushImg.zip'
extract_dir = "/content/ekush"
archive_format = "zip"
shutil.unpack_archive(filename, extract_dir, archive_format)

In [9]:
folders = [str(i) for i in range(21,60)]
subs = ['male','female']
my_path = []

for sub in subs:
    for folder in tqdm(folders):
        root_path = Path(f'/content/ekush/pad/{sub}_squre/{folder}')
        label = int(folder)-21
        files = os.listdir(root_path)
        files.sort()
        for f in files:
            if f != 'Thumbs.db':
                my_path.append((root_path/f , label))
            else:
                print("FUCK")
    
len(my_path)

100%|██████████| 39/39 [00:00<00:00, 73.11it/s]


120950

In [10]:
my_path[21500]

(PosixPath('/content/ekush/pad/male_squre/35/0_CTG_18_2_600.jpg'), 14)

In [ ]:
target = Path('/content/capital')
if not os.path.isdir(target):
    os.mkdir(target)

for i in tqdm(my_path):
    original, num = i   
    file_name = (f"{num:02}_"+original.parts[-1])
    shutil.copyfile(original, target/file_name)
    

100%|██████████| 31542/31542 [00:03<00:00, 8471.89it/s]


In [11]:
new_files = os.listdir(target)
new_files.sort()

In [12]:
len(new_files)

77167

In [13]:
import requests, shutil, os, sys
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
from IPython.display import display
import numpy as np
import copy

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [14]:
target/new_files[46295]

PosixPath('/content/capital/23_02_0002_0_15_1016_1648_35.png')

In [15]:
def read_img(path):
    return copy.deepcopy(mpimg.imread(path))

def save_img(path, image):
    mpimg.imsave(path, image)


def mono2rgb(img):
    if len(img.shape) == 3:
        return img
    return np.stack((img,img,img),axis=-1)



def show_img(lis,titles = ()):
    fig = make_subplots(
        rows=1, cols=len(lis),
        subplot_titles=(titles)
    )
    for i in range(len(lis)):
        fig.add_trace(px.imshow(lis[i]).data[0],row = 1, col = i+1)
    
    fig.show()

In [16]:
read_img(target/new_files[46295])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
images = []

In [24]:
for new_file in tqdm(new_files):
    img = read_img(target/new_file)
    img = mono2rgb(img)
    if 255 in img:
        img = img / 255
    #img = mono2rgb(cv2.cvtColor(img, cv2.COLOR_RGB2GRAY))
    img = cv2.resize(img, (384,384))
    img = (1.0*(img>0.2)).astype(np.float32)
    
    img = img.astype(np.float32)

    save_img(target/new_file,img)




100%|██████████| 77167/77167 [35:28<00:00, 36.25it/s]


In [25]:
output_filename = "/content/drive/MyDrive/Colab Notebooks/pathshala/sorted/bangla/capital/lekha_1"
dir_name = "/content/capital"

In [26]:
shutil.make_archive(output_filename, 'zip', dir_name)

'/content/drive/MyDrive/Colab Notebooks/pathshala/sorted/bangla/capital/lekha_1.zip'

In [ ]:
255 in img

True

In [27]:
i = 6325
img = read_img(target/new_files[i])
print(target/new_files[i])
show_img([mono2rgb(img)],titles=('Threshold Image',))

Output hidden; open in https://colab.research.google.com to view.

In [21]:
i = 32155
img = read_img(target/new_files[i])
print(target/new_files[i])
show_img([mono2rgb(img)],titles=('Threshold Image',))

/content/capital/16_01_0001_1_16_0916_0292_28.png


In [23]:
i = 46050
img = read_img(target/new_files[i])
print(target/new_files[i])
img = mono2rgb(img)
if 255 in img:
    img = img / 255
#img = mono2rgb(cv2.cvtColor(img, cv2.COLOR_RGB2GRAY))
img = cv2.resize(img, (384,384))
img = (1.0*(img>0.2)).astype(np.float32)

img = img.astype(np.float32)

show_img([img])

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
img

array([[[0.9529412 , 0.94509804, 0.98039216],
        [0.9529412 , 0.9490196 , 0.9764706 ],
        [0.9490196 , 0.9490196 , 0.972549  ],
        ...,
        [0.9529412 , 0.9490196 , 0.98039216],
        [0.9529412 , 0.9529412 , 0.9764706 ],
        [0.9490196 , 0.9529412 , 0.9764706 ]],

       [[0.9529412 , 0.94509804, 0.98039216],
        [0.9529412 , 0.9490196 , 0.9764706 ],
        [0.9490196 , 0.9490196 , 0.98039216],
        ...,
        [0.9490196 , 0.9490196 , 0.9764706 ],
        [0.9490196 , 0.9529412 , 0.9764706 ],
        [0.9529412 , 0.95686275, 0.9764706 ]],

       [[0.9529412 , 0.9490196 , 0.98039216],
        [0.9529412 , 0.9490196 , 0.98039216],
        [0.9490196 , 0.9490196 , 0.98039216],
        ...,
        [0.94509804, 0.9372549 , 0.9764706 ],
        [0.94509804, 0.9411765 , 0.972549  ],
        [0.9490196 , 0.94509804, 0.972549  ]],

       ...,

       [[0.94509804, 0.9372549 , 0.96862745],
        [0.9411765 , 0.92941177, 0.96862745],
        [0.9372549 , 0

In [ ]:
img = cv2.resize(img, (384,384))

In [ ]:
img = mono2rgb(img)
img = mono2rgb(cv2.cvtColor(img, cv2.COLOR_RGB2GRAY))
img = (1.0*(img>0.8)).astype(np.float32)

In [ ]:
closing_SE_size = 3
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(closing_SE_size,closing_SE_size))
img = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel = kernel)

In [ ]:
kernel_size = 3
img = cv2.erode(img,kernel =  np.ones((kernel_size,kernel_size),np.float32) ,iterations = 1)

In [ ]:
img

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [ ]:
show_img([mono2rgb(img)],titles=('Threshold Image',))

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
show_img([mono2rgb(img)],titles=('Threshold Image',))

In [ ]:
folder = 'a'
root_path = Path(f'/content/Numta_Workshop/training-{folder}')
root_path

PosixPath('/content/Numta_Workshop/training-a')

In [ ]:
str(root_path)

'/content/Numta_Workshop/training-a'

In [ ]:
name = pd.read_csv(str(root_path)+'.csv')
name = name.set_index('filename')
name = name[['digit']]
name

digit
filename         
a00000.png      5
a00001.png      3
a00002.png      1
a00003.png      7
a00004.png      0
...           ...
a19697.png      4
a19698.png      3
a19699.png      8
a19700.png      3
a19701.png      8

[19702 rows x 1 columns]

In [ ]:
name = name.to_dict()
name

In [ ]:
name['digit']['a00078.png']

In [ ]:
files = os.listdir(root_path)
files.sort()
#files = files[1:]
files